<div class="xwzx1">
            <div class="xwzx1-1"> <a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" width="100%" /></a> </div>
            <div class="xwzx1-2">
              <h2><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2>
              <p>[field:description function="cn_substr(@me,240)"/]...</p>
              <h3><span>发布时间：[field:pubdate function="MyDate('Y-m-d',@me)"/]</span> <span>浏览次数：[field:click/]</span></h3>
            </div>
            <br class="clear" />
          </div>