<?php
$z[0]=Array("arcurl","",64,79);
$z[1]=Array("title","",88,102);
$z[2]=Array("picname","",114,130);
$z[3]=Array("arcurl","",222,237);
$z[4]=Array("title","",246,260);
$z[5]=Array("title","",262,276);
$z[6]=Array("description","",304,354);
$z[6][4]['function']="cn_substr(@me,240)";
$z[7]=Array("pubdate","",402,449);
$z[7][4]['function']="MyDate('Y-m-d',@me)";
$z[8]=Array("click","",478,492);

?>