<?php
$z[0]=Array("global","",124,156);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("channelartlist","\r\n      <li class='{dede:field.currentstyle/}'><a href=\"{dede:field name='typeurl'/}\" class=\"nav-a\">{dede:field name='typename'/}</a>\r\n        <ul class=\"list-unstyled\">\r\n          {dede:channel type='son' noself='yes'}\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n          {/dede:channel}\r\n        </ul>\r\n      </li>\r\n      ",461,896);
$z[1][4]['typeid']="top";
$z[1][4]['currentstyle']="hover";
$z[1][4]['row']="7";
$z[2]=Array("arclist","\r\n    <div class=\"cell\">\r\n      <div class=\"con\" style=\"background-image:url([field:picname/]);\"> </div>\r\n    </div>\r\n    ",1017,1190);
$z[2][4]['typeid']="32";
$z[2][4]['row']="10";

?>